# Generated by Django 3.2.3 on 2021-05-19 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('number', models.PositiveSmallIntegerField(help_text='Number of the bill', primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('arr', 'Arrival'), ('dep', 'Departure')], default='dep', help_text='Type of operation', max_length=3)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.PositiveSmallIntegerField(help_text='Vertical section number on a warehouse scheme', verbose_name='Section')),
            ],
            options={
                'ordering': ['row', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(help_text='Product barcode', max_length=128, null=True)),
                ('article', models.CharField(blank=True, help_text='Name of product', max_length=128)),
                ('description', models.TextField(help_text='Description of product', max_length=1000)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer name (e.g. BOSCH, Samsung)', max_length=128)),
                ('model', models.CharField(blank=True, help_text='Model of the product', max_length=128, verbose_name='Model')),
                ('length', models.PositiveSmallIntegerField(default=0, help_text='Length of the product (in cm)')),
                ('width', models.PositiveSmallIntegerField(default=0, help_text='Width of the product (in cm)')),
                ('height', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Height of the product (in cm)')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight of a good (in kg)', max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of a good (in rubles)', max_digits=10)),
                ('fragile', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('number', models.PositiveSmallIntegerField(help_text="Number of cell's row on a warehouse scheme", primary_key=True, serialize=False)),
                ('storage', models.CharField(choices=[('HRS', 'Стеллаж'), ('PAL', 'Палета')], default='HRS', help_text='Type of storage (e.g. High Rack Storage, Pallet)', max_length=3)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='Level of the place')),
                ('length', models.PositiveSmallIntegerField(help_text='Length of the place (in cm)')),
                ('width', models.PositiveSmallIntegerField(help_text='Width of the place (in cm)')),
                ('height', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Height of the place (in cm)')),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum available weight on the place (in kg)', max_digits=7)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wms.cell')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='GoodInstance',
            fields=[
                ('goodinstance_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufactured', models.DateField(null=True)),
                ('best_before', models.DateField(blank=True, null=True, verbose_name='Best before')),
                ('bill', models.ManyToManyField(blank=True, to='wms.Bill')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.good')),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='wms.place')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.row'),
        ),
    ]
