# Generated by Django 3.2.3 on 2021-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer name (e.g. BOSCH, Samsung', max_length=128),
        ),
        migrations.AddField(
            model_name='good',
            name='model',
            field=models.CharField(blank=True, help_text='Model of the product', max_length=128, verbose_name='Model'),
        ),
    ]
