# Generated by Django 3.2.3 on 2021-05-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_good_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinstance',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='wms.place'),
        ),
    ]
