# Generated by Django 3.2.3 on 2021-05-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_alter_goodinstance_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='article',
            field=models.CharField(blank=True, help_text='Name of product', max_length=128, unique=True),
        ),
    ]
