# Generated by Django 3.2.3 on 2021-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_alter_good_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinstance',
            name='best_before',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Best before'),
        ),
        migrations.AlterField(
            model_name='goodinstance',
            name='manufactured',
            field=models.DateField(help_text='YYYY-MM-DD', null=True),
        ),
    ]
